#----------------------------------------------------------------------------------------------#
#                                                                                              #
#                                   KUBEDOM-API properties                                  #
#                                                                                              #
#----------------------------------------------------------------------------------------------#
server:
  port: 8081

spring:
  application:
    name: kubedom-api
  main:
    banner-mode: "off"
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/kubedom}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:pgpass1289}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format-sql: true

security:
  enabled: false

app:
  ova-location: "https://www.kubedom.borisgk.space/static/customer-node.ova"